engines:
  eslint:
    enabled: true
  pylint:
    enabled: true

ignore_patterns:
  - "tests/*"

eslint:
  enabled: true
  config_file: .eslintrc.json
  exclude_paths:
    - 'tests/**'

exclude_paths:
    - 'tests/**'